name: riverpod_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  busslina_dart_lightweight_lib:
    path: ../../../DART/LIBS/busslina-dart-lightweight-lib
  busslina_flutter_lightweight_lib:
    path: ../..//LIBS/busslina-flutter-lightweight-lib
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.5
  fast_immutable_collections: ^9.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
